### ISSUE TITLE
Crash mixin 

### ISSUE THREAD

**Issue by JustFoxx** [EyezahMC/Cosmetica#50]
Basically, when the window of game i showing it immediately crashes with mixin error in cosmetica.mixins.json:textures.MixinCapeLayer
Version 1.18.2 fabric
```
11:44:43.716
FabricLoader/Mixin
Render thread
@Redirect conflict. Skipping cosmetica.mixins.json:textures.MixinCapeLayer from mod cosmetica->@Redirect::allowTransparentCapes(Lnet/minecraft/class_2960;)Lnet/minecraft/class_1921; with priority 1000, already redirected by capes.mixins.json:MixinCapeFeatureRenderer from mod capes->@Redirect::fixCapeTransparency(Lnet/minecraft/class_2960;)Lnet/minecraft/class_1921; with priority 1000
11:44:43.717
FabricLoader
Render thread
Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_972 failed
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_972 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.launch.knot.MixinServiceKnot.findClass(MixinServiceKnot.java:96)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.audit(MixinProcessor.java:254)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.audit(MixinTransformer.java:171)
	at org.spongepowered.asm.mixin.MixinEnvironment.audit(MixinEnvironment.java:1425)
	at ca.fxco.memoryleakfix.MemoryLeakFix.forceLoadAllMixinsAndClearSpongePoweredCache(MemoryLeakFix.java:25)
	at net.minecraft.client.main.Main.redirect$edh000$loadAllMixinsThenShouldRenderAsync(Main:525)
	at net.minecraft.client.main.Main.main(Main:212)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414)
	... 16 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector allowTransparentCapes(Lnet/minecraft/class_2960;)Lnet/minecraft/class_1921; in cosmetica.mixins.json:textures.MixinCapeLayer from mod cosmetica failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap cosmetics-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 19 more
```

**Comment by JustFoxx** [comment]
ok so i found out that there is  incompatibility Fbaric Capes with Cosmetica (woud be cool if that was said in mod files rather than crash >.>)

**Comment by eyezahhhh** [comment]
We plan on adding more obvious mod incompatibility warnings in future. Closing as the issue as been resolved.
